on: [push]

jobs:
  readme_examples:
    runs-on: ubuntu-latest
    name: Checks if all examples are listed in the examples/README.md
    steps:
      # To use 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Example Checker
        uses: ./ # uses an action in the root directory
        id: example
        # with:
          # who-to-greet: 'Mona the Rugby player'
    # Use the output from the `hello` step
      # - name: Get the output time
        # run: echo "The time was ${{ steps.hello.outputs.time }}"